main: io.github.stonley890.eyeofonyx.EyeOfOnyx
name: EyeOfOnyx
version: 1.0.0
api-version: 1.19
description: A plugin that manages the royalty board on Wings of Fire The New World
authors: [Stonley890, iHeron]
website: https://github.com/Stonley890/EyeOfOnyx
depend: [Dreamvisitor]
softdepend:
  - OpenRP

commands:
  eyeofonyx:
    description: Manage Eye of Onyx.
    usage: /<command> <ban|unban|freeze|disable|config>
  royalty:
    description: Access or manage the royalty board.
    usage: /<command> <set|list|clear|update|manage>
  challenge:
    description: Initiate a challenge.
    usage: /<command>
  tribeupdate:
    description: Update Discord role based on in-game team
    usage: /<command> [player]
    permission: minecraft.command.op

permissions:
  eyeofonyx.manageboard:
    description: Allows editing the royalty board.
    default: op
  eyeofonyx.ban:
    description: Manage royalty bans.
    default: op