package io.github.stonley890.eyeofonyx.files;

public enum NotificationType {

    GENERIC, CHALLENGE_REQUESTED, CHALLENGE_ACCEPTED, COOLDOWN_END, REMOVED_INACTIVITY, REMOVED_BANNED, REMOVED_TRIBE, REMOVED_GENERIC, PROMOTED

}
