# The address to use for the challenge availability web interface.
# Default: "https://eyeofonyx.woftnw.org"
address: "https://eyeofonyx.woftnw.org"

# The port to use for the challenge availability web interface.
# You'll need to forward this on your network.
# If not set, it will fall back to the default 8000.
# Default: 8000
port: 8000

# Whether the royalty board is frozen.
# This prevents players from leaving the royalty board or initiating challenges.
# This can be toggled using /eyeofonyx freeze
# Default: false
frozen: false

# The name of the field where a character's name is stored in OpenRP.
# OpenRP uses "name" by default. It can be changed in OpenRP/descriptions/config.yml.
# Don't change this if you don't know what this is.
# Default: "name"
character-name-field: "name"

# The channel ID for the Discord channel where the royalty board should be stored.
# Default: 913509632348139591
royalty-board-channel: 913509632348139591

# The channel ID for the Discord channel where updates to the royalty board should be recorded.
# Default: 660597606233276436
royalty-log-channel: 660597606233276436

# The message IDs for the messages containing the royalty board.
# This is set automatically by Eye of Onyx.
royalty-board-message:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0

# The royalty role IDs for the main server
main-royalty-roles: {
  ruler: 685296904741191778,
  heir: 796072595798622279,
  noble: 916438547232325642
}

# Cool down period:
# The number of DAYS that a user is unable to participate in a challenge after they have moved.
# Default: 7
challenge-cool-down: 7

# Challenge acknowledgement period:
# The number of DAYS that a user has to acknowledge a challenge that has been issued to them.
# Default: 7
challenge-acknowledgement-time: 7

# Challenge time period:
# The maximum number of DAYS from challenge acknowledgement that a challenge can be scheduled.
# Default: 7
challenge-time-period: 7

# Time selection period:
# The number of DAYS a challenger is allotted to select one of the provided times.
# Default: 3
time-selection-period: 3

# Inactivity timer:
# The number of DAYS that a user can be offline before they are removed from the royalty board.
# Default: 30
inactivity-timer: 30

# Challenge waiting room location:
# The locations of the challenge waiting rooms.
# This should be set with /eyeofonyx config waiting-rooms <tribe> <x> <y> <z>
# Do not change this unless you know what you're doing.
waiting-rooms:
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null

# Below are the permission groups for LuckPerms.
# This can be set in-game with /eyeofonyx config lp.<position> <name>
# The defaults match with the current names (as of release).
ruler: {
  hive: "hivewing_ruler",
  ice: "icewing_ruler",
  leaf: "leafwing_ruler",
  mud: "mudwing_ruler",
  night: "nightwing_ruler",
  rain: "rainwing_ruler",
  sand: "sandwing_ruler",
  sea: "seawing_ruler",
  silk: "silkwing_ruler",
  sky: "skywing_ruler"
}
heir: {
  hive: "hivewing_heir",
  ice: "icewing_heir",
  leaf: "leafwing_heir",
  mud: "mudwing_heir",
  night: "nightwing_heir",
  rain: "rainwing_heir",
  sand: "sandwing_heir",
  sea: "seawing_heir",
  silk: "silkwing_heir",
  sky: "skywing_heir"
}
noble: {
  hive: "hivewing_noble",
  ice: "icewing_noble",
  leaf: "leafwing_noble",
  mud: "mudwing_noble",
  night: "nightwing_noble",
  rain: "rainwing_noble",
  sand: "sandwing_noble",
  sea: "seawing_noble",
  silk: "silkwing_noble",
  sky: "skywing_noble"
}
citizen: {
  hive: "hivewing_citizen",
  ice: "icewing_citizen",
  leaf: "leafwing_citizen",
  mud: "mudwing_citizen",
  night: "nightwing_citizen",
  rain: "rainwing_citizen",
  sand: "sandwing_citizen",
  sea: "seawing_citizen",
  silk: "silkwing_citizen",
  sky: "skywing_citizen"
}

# Images for each of the tribes.
# Used for the royalty board and log messages.
tribe-emblems:
  - "https://cdn.discordapp.com/emojis/1059550841939431434.webp?size=44&quality=lossless"
  - "https://cdn.discordapp.com/emojis/848783045960269855.webp?size=44&quality=lossless"
  - 'https://cdn.discordapp.com/emojis/1059550991025971342.webp?size=44&quality=lossless'
  - "https://cdn.discordapp.com/emojis/848783194912587798.webp?size=44&quality=lossless"
  - "https://cdn.discordapp.com/emojis/848782864060514395.webp?size=44&quality=lossless"
  - "https://cdn.discordapp.com/emojis/848783641080233984.webp?size=44&quality=lossless"
  - "https://cdn.discordapp.com/emojis/848781744315826196.webp?size=44&quality=lossless"
  - "https://cdn.discordapp.com/emojis/848783311815573554.webp?size=44&quality=lossless"
  - "https://cdn.discordapp.com/emojis/1059550024704463019.webp?size=44&quality=lossless"
  - "https://cdn.discordapp.com/emojis/848781745038163978.webp?size=44&quality=lossless"
