main: io.github.stonley890.Main
name: EyeOfOnyx
version: 1.0.0
api-version: 1.19
description: A plugin that manages the royalty board on Wings of Fire The New World
authors: [Stonley890, iHeron]
website: https://github.com/Stonley890/EyeOfOnyx
depend: [Dreamvisitor]

commands:
  eyeofonyx:
    description: Report Eye of Onyx version.
    usage: /<command>
    permission: minecraft.command.op
  royalty:
    description: Access or manage the royalty board.
    usage: /<command> <set|remove|list>
    permission: minecraft.command.op